basePath: /
definitions:
  handlers.Message:
    properties:
      message:
        type: string
    type: object
host: localhost:4040
info:
  contact: {}
  description: This is a simple Gin application with Swagger documentation.
  title: MyApp API
  version: "1.0"
paths:
  /api/goodbye:
    post:
      description: Post a goodbye message
      parameters:
      - description: Message
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/handlers.Message'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Message'
      summary: Returns a goodbye message
      tags:
      - example
  /api/hello:
    get:
      description: Get a hello message
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Message'
      summary: Returns a hello message
      tags:
      - example
swagger: "2.0"
